// Generated by https://quicktype.io

export interface IsAuthorJSON {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  can_edit: boolean
  forbid: boolean
  id: number
  is_author: boolean
  level: boolean
}
