// Generated by https://quicktype.io

export interface AuthCodeJson {
  code: number
  message: string
  ttl: number
  data: AuthCodeData
}

export interface AuthCodeData {
  url: string
  auth_code: string
}
