// Generated by https://quicktype.io

export interface ListBlackJson {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  list: BlackItem[]
  re_version: number
  total: number
}

export interface BlackItem {
  mid: number
  attribute: number
  mtime: number
  tag: null
  special: number
  uname: string
  face: string
  sign: string
  face_nft: number
  official_verify: OfficialVerify
  vip: Vip
  nft_icon: string
  rec_reason: string
  track_id: string
}

export interface OfficialVerify {
  type: number
  desc: string
}

export interface Vip {
  vipType: number
  vipDueDate: number
  dueRemark: string
  accessStatus: number
  vipStatus: number
  vipStatusWarn: string
  themeType: number
  label: Label
  avatar_subscript: number
  nickname_color: string
  avatar_subscript_url: string
}

export interface Label {
  path: string
  text: string
  label_theme: string
  text_color: string
  bg_style: number
  bg_color: string
  border_color: string
}
