// Generated by https://quicktype.io

export interface DynamicPortalJSON {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  live_users: LiveUsers
  my_info: MyInfo
  up_list: DynamicPortalUp[]
}

export interface LiveUsers {
  count: number
  group: string
  items: Item[]
}

export interface Item {
  face: string
  is_reserve_recall: boolean
  jump_url: string
  mid: number
  room_id: number
  title: string
  uname: string
}

export interface MyInfo {
  dyns: number
  face: string
  face_nft: number
  follower: string
  following: number
  level_info: LevelInfo
  mid: number
  name: string
  official: Official
  space_bg: string
  vip: Vip
}

export interface LevelInfo {
  current_exp: number
  current_level: number
  current_min: number
  level_up: number
  next_exp: number
}

export interface Official {
  desc: string
  role: number
  title: string
  type: number
}

export interface Vip {
  avatar_subscript: number
  avatar_subscript_url: string
  due_date: number
  label: Label
  nickname_color: string
  role: number
  status: number
  theme_type: number
  tv_due_date: number
  tv_vip_pay_type: number
  tv_vip_status: number
  type: number
  vip_pay_type: number
}

export interface Label {
  bg_color: string
  bg_style: number
  border_color: string
  img_label_uri_hans: string
  img_label_uri_hans_static: string
  img_label_uri_hant: string
  img_label_uri_hant_static: string
  label_theme: string
  path: string
  text: string
  text_color: string
  use_img_label: boolean
}

export interface DynamicPortalUp {
  face: string
  has_update: boolean
  is_reserve_recall: boolean
  mid: number
  uname: string
}
