// Generated by https://quicktype.io

export interface PopularWeeklyJson {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  config: Config
  reminder: string
  list: PopularWeeklyItem[]
}

export interface Config {
  id: number
  type: string
  number: number
  subject: string
  stime: number
  etime: number
  status: number
  name: string
  label: string
  hint: string
  color: number
  cover: string
  share_title: string
  share_subtitle: string
  media_id: number
}

export interface PopularWeeklyItem {
  aid: number
  videos: number
  tid: number
  tname: string
  copyright: number
  pic: string
  title: string
  pubdate: number
  ctime: number
  desc: string
  state: number
  duration: number
  rights: { [key: string]: number }
  owner: Owner
  stat: { [key: string]: number }
  dynamic: string
  cid: number
  dimension: Dimension
  short_link_v2: string
  first_frame: string
  pub_location: string
  bvid: string
  season_type: number
  is_ogv: boolean
  ogv_info: null
  enable_vt: number
  ai_rcmd: null
  rcmd_reason: string
  mission_id?: number
  up_from_v2?: number
  season_id?: number
}

export interface Dimension {
  width: number
  height: number
  rotate: number
}

export interface Owner {
  mid: number
  name: string
  face: string
}
