// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface PvideoJson {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  pvdata: string
  img_x_len: number
  img_y_len: number
  img_x_size: number
  img_y_size: number
  image: string[]
  index: number[]
}
