// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface RecommendJson {
  code: number
  config: Config
  data: RecItem[]
  message: string
}

export interface Config {
  feed_clean_abtest: number
}

export interface RecItem {
  title: string
  cover: string
  uri: string
  param: string
  goto: Goto
  desc: string
  play: number
  danmaku?: number
  reply?: number
  favorite: number
  coin?: number
  share?: number
  like?: number
  duration?: number
  idx: number
  cid?: number
  tid?: number
  tname?: string
  tag?: Tag
  dislike_reasons?: DislikeReason[]
  ctime?: number
  autoplay?: number
  mid?: number
  name?: string
  face: string
  autoplay_card?: number
  type?: number
  badge?: string
  square?: string

  // 推荐理由
  rcmd_reason?: { id: number; content: string }
}

export interface DislikeReason {
  reason_id: number
  reason_name: string
}

export enum Goto {
  AV = 'av',
  Bangumi = 'bangumi',
}

export interface Tag {
  tag_id: number
  tag_name: string
  count: Count
}

export interface Count {
  atten?: number
}
