// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface WatchLaterJson {
  code: number
  message: string
  ttl: number
  data: Data
}

export interface Data {
  count: number
  list: WatchLaterItem[]
}

export interface WatchLaterItem {
  aid: number
  videos: number
  tid: number
  tname: string
  copyright: number
  pic: string
  title: string
  pubdate: number
  ctime: number
  desc: string
  state: number
  duration: number
  rights: { [key: string]: number }
  owner: Owner
  stat: { [key: string]: number }
  dynamic: string
  dimension: Dimension
  season_id?: number
  short_link_v2: string
  first_frame?: string
  pub_location?: string
  pages: Page[]
  cid: number
  progress: number
  add_at: number
  bvid: string
  uri: string
  viewed: boolean
  seq: number
  enable_vt: number
  up_from_v2?: number
  mission_id?: number
}

export interface Dimension {
  width: number
  height: number
  rotate: number
}

export interface Owner {
  mid: number
  name: string
  face: string
}

export interface Page {
  cid: number
  page: number
  from: From
  part: string
  duration: number
  vid: string
  weblink: string
  dimension: Dimension
  first_frame?: string
}

export enum From {
  Vupload = 'vupload',
}
