/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Fragment: typeof import('react')['Fragment']
  const IconIonLayersOutline: typeof import('~icons/ion/layers-outline.jsx')['default']
  const IconLetsIconsViewHide: typeof import('~icons/lets-icons/view-hide.jsx')['default']
  const IconLucideFolder: typeof import('~icons/lucide/folder.jsx')['default']
  const IconLucideFolderLock: typeof import('~icons/lucide/folder-lock.jsx')['default']
  const IconLucideList: typeof import('~icons/lucide/list.jsx')['default']
  const IconMaterialSymbolsBarChart: typeof import('~icons/material-symbols/bar-chart.jsx')['default']
  const IconMaterialSymbolsDeleteOutlineRounded: typeof import('~icons/material-symbols/delete-outline-rounded.jsx')['default']
  const IconMaterialSymbolsLightOpenInNew: typeof import('~icons/material-symbols-light/open-in-new.jsx')['default']
  const IconMaterialSymbolsLightOpenInNewOff: typeof import('~icons/material-symbols-light/open-in-new-off.jsx')['default']
  const IconMdiShuffleDisabled: typeof import('~icons/mdi/shuffle-disabled.jsx')['default']
  const IconMynauiUsersGroup: typeof import('~icons/mynaui/users-group.jsx')['default']
  const IconParkOutlineAddTwo: typeof import('~icons/icon-park-outline/add-two.jsx')['default']
  const IconParkOutlineClose: typeof import('~icons/icon-park-outline/close.jsx')['default']
  const IconParkOutlineComputer: typeof import('~icons/icon-park-outline/computer.jsx')['default']
  const IconParkOutlineConcern: typeof import('~icons/icon-park-outline/concern.jsx')['default']
  const IconParkOutlineConfig: typeof import('~icons/icon-park-outline/config.jsx')['default']
  const IconParkOutlineCopy: typeof import('~icons/icon-park-outline/copy.jsx')['default']
  const IconParkOutlineDistraughtFace: typeof import('~icons/icon-park-outline/distraught-face.jsx')['default']
  const IconParkOutlineDownC: typeof import('~icons/icon-park-outline/down-c.jsx')['default']
  const IconParkOutlineDrag: typeof import('~icons/icon-park-outline/drag.jsx')['default']
  const IconParkOutlineFire: typeof import('~icons/icon-park-outline/fire.jsx')['default']
  const IconParkOutlineHelp: typeof import('~icons/icon-park-outline/help.jsx')['default']
  const IconParkOutlineInfo: typeof import('~icons/icon-park-outline/info.jsx')['default']
  const IconParkOutlineIphone: typeof import('~icons/icon-park-outline/iphone.jsx')['default']
  const IconParkOutlineLoading: typeof import('~icons/icon-park-outline/loading.jsx')['default']
  const IconParkOutlinePeopleDelete: typeof import('~icons/icon-park-outline/people-delete.jsx')['default']
  const IconParkOutlinePeopleMinus: typeof import('~icons/icon-park-outline/people-minus.jsx')['default']
  const IconParkOutlinePeopleSearch: typeof import('~icons/icon-park-outline/people-search.jsx')['default']
  const IconParkOutlinePlayTwo: typeof import('~icons/icon-park-outline/play-two.jsx')['default']
  const IconParkOutlineReturn: typeof import('~icons/icon-park-outline/return.jsx')['default']
  const IconParkOutlineStar: typeof import('~icons/icon-park-outline/star.jsx')['default']
  const IconParkOutlineTime: typeof import('~icons/icon-park-outline/time.jsx')['default']
  const IconParkOutlineTips: typeof import('~icons/icon-park-outline/tips.jsx')['default']
  const IconParkOutlineTumblr: typeof import('~icons/icon-park-outline/tumblr.jsx')['default']
  const IconParkSolidStar: typeof import('~icons/icon-park-solid/star.jsx')['default']
  const IconPhThumbsDownDuotone: typeof import('~icons/ph/thumbs-down-duotone.jsx')['default']
  const IconRadixIconsPerson: typeof import('~icons/radix-icons/person.jsx')['default']
  const IconSvgSpinnersBarsRotateFade: typeof import('~icons/svg-spinners/bars-rotate-fade.jsx')['default']
  const IconTablerFaceIdError: typeof import('~icons/tabler/face-id-error.jsx')['default']
  const IconTablerPlus: typeof import('~icons/tabler/plus.jsx')['default']
  const IconTablerSortAscending2: typeof import('~icons/tabler/sort-ascending2.jsx')['default']
  const IconTablerSortDescending2: typeof import('~icons/tabler/sort-descending2.jsx')['default']
  const clsx: typeof import('clsx')['clsx']
  const createRef: typeof import('react')['createRef']
  const createRoot: typeof import('react-dom/client')['createRoot']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const size: typeof import('polished')['size']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useKeyPress: typeof import('ahooks')['useKeyPress']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMemoizedFn: typeof import('ahooks')['useMemoizedFn']
  const useMount: typeof import('ahooks')['useMount']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useUpdateEffect: typeof import('ahooks')['useUpdateEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ComponentProps, CSSProperties, ReactNode, RefObject } from 'react'
  import('react')
  // @ts-ignore
  export type { Root } from 'react-dom/client'
  import('react-dom/client')
}
